/* ============================================================
   Nocturne — config, seed contacts & welcome mail
   Cardano by day. Nocturne by night.
   ============================================================ */

const NOCTURNE = {
  name: 'Nocturne',
  tagline: 'Private messaging on Midnight',
  domain: 'nocturne.night',

  /* --- Socials ------------------------------------------------ */
  x: {
    handle: '@kshot9000',
    url: 'https://x.com/kshot9000'
  },

  /* --- Donations (carried over from the earlier sites) -------- */
  donate: [
    {
      id: 'ADA',
      label: 'Cardano (ADA)',
      addr: 'addr1q8hnl6vl5a6k3rw3n5g3jtte696zcl76kfatzv7gpswa9r0dj7fma6klq55y4ffm7tf0em09udnyhuk4ah92pl5x9jpqjae44v',
      view: 'https://cardanoscan.io/addresses/addr1q8hnl6vl5a6k3rw3n5g3jtte696zcl76kfatzv7gpswa9r0dj7fma6klq55y4ffm7tf0em09udnyhuk4ah92pl5x9jpqjae44v',
      color: '#9a9a9a'
    },
    {
      id: 'BTC',
      label: 'Bitcoin (BTC)',
      addr: '3GnR7TWBXAB3pPztBWpNF4LMNEX5yX8vZK',
      view: 'https://mempool.space/address/3GnR7TWBXAB3pPztBWpNF4LMNEX5yX8vZK',
      color: '#cfcfcf'
    },
    {
      id: 'ERG',
      label: 'Ergo (ERG)',
      addr: '9fcM5RWnAjmP4vx5bnW6yohB6H9bLq8sJbaPLHtwZLtQPB32Pvy',
      view: 'https://explorer.ergoplatform.com/addresses/9fcM5RWnAjmP4vx5bnW6yohB6H9bLq8sJbaPLHtwZLtQPB32Pvy',
      color: '#b3b3b3'
    }
  ],

  /* --- Assets available in the send flow ----------------------- */
  assets: [
    {
      id: 'NIGHT',
      name: 'Midnight',
      ticker: 'NIGHT',
      color: '#ffffff',
      icon: 'moon',
      precision: 6,
      fee: 0.0005,
      feeLabel: 'DUST fee — generated by NIGHT (demo)',
      addrHint: 'mid1… or 38–64 char Midnight address',
      validate: (v) =>
        /^mid1[0-9a-z]{20,90}$/i.test(v) || /^[a-z0-9]{38,64}$/i.test(v)
    },
    {
      id: 'ADA',
      name: 'Cardano',
      ticker: 'ADA',
      color: '#9a9a9a',
      icon: 'cardano',
      precision: 6,
      fee: 0.25,
      feeLabel: '0.25 ADA (demo fee)',
      addrHint: 'addr1… (bech32 Shelley address)',
      validate: (v) => /^addr1[a-z0-9]{20,120}$/.test(v)
    },
    {
      id: 'BTC',
      name: 'Bitcoin',
      ticker: 'BTC',
      color: '#cfcfcf',
      icon: 'btc',
      precision: 8,
      fee: 0.00002,
      feeLabel: '0.00002 BTC (demo fee)',
      addrHint: 'bc1… (bech32) or 1… / 3… (legacy)',
      validate: (v) =>
        /^bc1[a-z0-9]{20,90}$/.test(v) ||
        /^[13][a-km-zA-HJ-NP-Z1-9]{25,34}$/.test(v)
    }
  ],

  /* --- Seeded residents (demo contacts) ------------------------ */
  contacts: [
    {
      id: 'nocturne',
      handle: 'nocturne',
      name: 'Nocturne Concierge',
      system: true,
      color: '#ffffff',
      online: true,
      welcome:
        'Welcome to the quiet side of Cardano, {handle}. I am the concierge — ask me about your mailbox, sending NIGHT/ADA/BTC, or how the encryption works.',
      replies: [
        'Noted. Everything you store here is sealed with AES-256-GCM before it touches this browser’s storage.',
        'Tip: open the Send tab to move NIGHT, ADA or BTC. The QR in the review step is real and scannable.',
        'Your mailbox is {handle}@nocturne.night. Mail you send lands in the Sent folder.',
        'Remember: Nocturne has no server. When this tab’s storage clears, the dark takes it back.',
        'Ask me again if you like — I never sleep, which is the point of the name.',
        'Midnight tip: programmable privacy — everything stays shielded, and only what’s necessary gets disclosed, when it’s necessary. That’s the zero-knowledge way.'
      ]
    },
    {
      id: 'moon_whisper',
      handle: 'moon_whisper',
      name: 'Moon Whisper',
      color: '#ffffff',
      online: true,
      welcome:
        'You found the quiet channel, {handle}. Moonlight travels fast; gossip doesn’t. What’s on your mind?',
      replies: [
        'The moon doesn’t send receipts. But I can see you read that.',
        'I was just watching Midnight’s ledger breathe — public state up top, private state under the blanket. It hums in B-flat, if you squint.',
        'Keep your keys like a lullaby — only you should know the words.',
        'I once forwarded a secret to a satellite. It bounced. Poetic, no?',
        'The dark isn’t empty, {handle}. It’s just listening.',
        'Send me your NIGHT and I’ll pretend it was always mine. (Demo, demo — nothing actually moves.)'
      ]
    },
    {
      id: 'ada_dev',
      handle: 'ada_dev',
      name: 'Ada Dev',
      color: '#9a9a9a',
      online: true,
      welcome:
        '{handle}! I ship Cardano stuff by day and lurk Midnight channels by night. P2P, Plutus, or just moon talk?',
      replies: [
        'Ha — “privacy by default, drama by exception.” I could tattoo that.',
        'If Nocturne ever gets a relay, I’m volunteering as the human load-balancer.',
        'My ADA address is in my bio. My secrets are in Nocturne. That’s the whole philosophy.',
        'Static site, zero servers. It’s the most “on-chain” feeling a website can get without being on-chain.',
        'Ship it. Then whisper about it. Then let the blocks settle.',
        '0x42, but make it midnight.'
      ]
    },
    {
      id: 'btc_ghost',
      handle: 'btc_ghost',
      name: 'BTC Ghost',
      color: '#cfcfcf',
      online: false,
      welcome:
        '*static* …you… talk to a ghost, {handle}? …fine. I lurk here. BTC forever. Midnight sometimes.',
      replies: [
        'Not much to say. Satoshis don’t whisper. They settle.',
        'I heard Midnight discloses only what’s necessary, when it’s necessary. In 2010 we called that “a cold wallet in a bunker.”',
        'My last message was 2016. I keep it as an artifact.',
        'Send BTC. I’ll haunt the mempool. (Demo. Nothing moves. Even ghosts don’t trust demos.)',
        '…',
        '*ghost appears to have left the dark*'
      ]
    }
  ],

  /* Generic reply pool for chats the user starts with new handles */
  genericReplies: [
    'Heard you over the quiet line. (This is a demo resident — no one is really there, which is rather the point.)',
    'Signal received. I will pretend to be someone important. (Demo mode.)',
    'Even ghosts need a “typing…” indicator. (Demo mode.)'
  ],

  /* --- Welcome mail (seeded into the inbox) --------------------- */
  welcomeMail: [
    {
      from: 'welcome@nocturne.night',
      name: 'Nocturne',
      subject: 'Welcome to the quiet side of Cardano',
      body:
        'Your private mailbox {handle}@nocturne.night is live.\n\n' +
        'This inbox lives only in your browser. It is sealed with AES-256-GCM ' +
        '(WebCrypto, right in your machine) before anything is written to storage, ' +
        'and there is no server holding a copy.\n\n' +
        'What you can do here:\n' +
        '• Chat with residents in the Messages tab\n' +
        '• Write mail to anyone at @nocturne.night (Sent folder keeps your copies)\n' +
        '• Send Midnight (NIGHT), Cardano (ADA) or Bitcoin (BTC) from the Send tab\n\n' +
        'Cardano by day. Nocturne by night.\n' +
        '— The Nocturne Concierge',
      read: false
    },
    {
      from: 'midnight@nocturne.night',
      name: 'Midnight Desk',
      subject: 'Programmable privacy',
      body:
        'Midnight is the fourth-generation blockchain of the Cardano ecosystem, ' +
        'built to bring rational privacy to blockchain: zero-knowledge proofs shield ' +
        'sensitive data, and programmable privacy decides exactly what gets ' +
        'disclosed — and when. NIGHT continuously generates DUST, the resource ' +
        'that powers transactions, so costs stay predictable.\n\n' +
        'Nocturne is what a conversation feels like at “private”: messages sealed ' +
        'end-to-end, a mailbox with no landlord, and money rails that don’t announce ' +
        'themselves.\n\n' +
        'Nothing in this mailbox has ever left your device. That is not a feature ' +
        'we added — it is a feature we refused to remove.',
      read: false
    },
    {
      from: 'treasury@nocturne.night',
      name: 'Nocturne Treasury',
      subject: 'Your keys, your coins',
      body:
        'A note before you send anything:\n\n' +
        'The Send tab builds a real, scannable QR of the recipient address and ' +
        'validates it per-chain (NIGHT, ADA, BTC). The broadcast step, however, is a ' +
        'simulation — Nocturne is a static site on GitHub Pages, so no transaction ' +
        'is ever signed or relayed from this browser.\n\n' +
        'Treat it as the design preview of a private money rail: the UX is final, ' +
        'the settlement is not (yet).\n\n' +
        'Keep the lights low.',
      read: false
    }
  ]
};
